"""
Tests for Exercise 02: Conditionals and Simple Loops
Generated by Copilot
"""

import sys
from pathlib import Path
import math
import pytest

# Add the exercise directory to the path so we can import the module
sys.path.insert(0, str(Path(__file__).parent))

import weather


@pytest.mark.parametrize(
    "temp,label",
    [
        (-10, "freezing"),
        (0, "freezing"),
        (1, "cold"),
        (10, "cold"),
        (11, "mild"),
        (20, "mild"),
        (21, "warm"),
        (30, "warm"),
        (31, "hot"),
        (45.5, "hot"),
    ],
)
def test_temperature_feel_labels(temp, label):
    assert weather.temperature_feel(temp) == label


@pytest.mark.parametrize(
    "forecast,count",
    [
        ([], 0),
        (["sunny"], 0),
        (["rainy"], 1),
        (["Rainy", "SUNNY", "RAINY", "cloudy"], 2),
        (["RAINY", "rainy", "RainY"], 3),
    ],
)
def test_count_rainy_days(forecast, count):
    assert weather.count_rainy_days(forecast) == count


@pytest.mark.parametrize(
    "temps,expected",
    [
        ([10, 15, 20], -1),
        ([21], 0),
        ([10, 20, 21], 2),
        ([19, 20, 20.0, 20.1], 3),
        ([30, 5, 6], 0),
    ],
)
def test_first_warm_day(temps, expected):
    assert weather.first_warm_day(temps) == expected


@pytest.mark.parametrize(
    "numbers,limit,expected",
    [
        ([], 10, 0),
        ([5], 10, 5),
        ([6], 5, 0),
        ([4, 4, 10], 9, 8),  # 4 + 4 = 8 (stop before 10 pushes over 9)
        ([2, 2, 2, 2, 2], 7, 6),
        ([3, 3, 3], 9, 9),
        ([1.5, 2.5, 3.0], 6.0, 6.0),
        ([1.5, 5.0, 0.1], 6.0, 1.5),
    ],
)
def test_sum_until_limit(numbers, limit, expected):
    result = weather.sum_until_limit(numbers, limit)
    assert math.isclose(result, expected)
