"""
Weather Reporter - Conditionals and Simple Loops Exercise
Generated by Copilot
"""

from typing import List, Union

Number = Union[int, float]

# TODO: Return a label based on the Celsius temperature
# "freezing" (<=0), "cold" (1-10), "mild" (11-20), "warm" (21-30), "hot" (>30)
def temperature_feel(temp_c: Number) -> str:
    pass


# TODO: Count how many entries equal "rainy" (case-insensitive)
# Ignore other values like "sunny", "cloudy", etc.
def count_rainy_days(forecast: List[str]) -> int:
    pass


# TODO: Return index of the first day with temperature strictly above 20
# If none, return -1
def first_warm_day(temps: List[Number]) -> int:
    pass


# TODO: Keep a running total from numbers without exceeding limit
# Stop adding when the next number would push the total above limit
# Return the total that does not exceed limit
def sum_until_limit(numbers: List[Number], limit: Number) -> Number:
    pass
