"""
Coffee Shop Order - Variables and Data Types Exercise
Generated by Copilot
"""

# TODO: Create a variable for the customer's name (string)
customer_name = 

# TODO: Create a variable for the drink size (string: "small", "medium", or "large")
drink_size = 

# TODO: Create a variable for the quantity of drinks ordered (integer)
quantity = 

# TODO: Create a variable for the price per drink (float)
price_per_drink = 

# TODO: Calculate the total price before discount, 
total_price = 

# TODO: Create a variable for loyalty membership status (boolean)
is_loyalty_member = 

# TODO: Use if to calculate the discount amount (0.0 if not a member, or 10% of total_price if member)

discount_amount = 

# TODO: Calculate the final price after discount (total_price - discount_amount)
final_price = 
