"""
Test file for Coffee Shop Order exercise
Generated by Copilot
"""

import pytest
import sys
from pathlib import Path

# Add the exercise directory to the path
sys.path.insert(0, str(Path(__file__).parent))

import order


def test_customer_name_exists():
    """Test that customer_name variable exists"""
    assert hasattr(order, 'customer_name')


def test_customer_name_is_string():
    """Test that customer_name is a string"""
    assert isinstance(order.customer_name, str)


def test_customer_name_not_empty():
    """Test that customer_name is not empty"""
    assert len(order.customer_name) > 0


def test_drink_size_exists():
    """Test that drink_size variable exists"""
    assert hasattr(order, 'drink_size')


def test_drink_size_is_string():
    """Test that drink_size is a string"""
    assert isinstance(order.drink_size, str)


def test_drink_size_valid():
    """Test that drink_size is one of the valid options"""
    assert order.drink_size.lower() in ['small', 'medium', 'large']


def test_quantity_exists():
    """Test that quantity variable exists"""
    assert hasattr(order, 'quantity')


def test_quantity_is_integer():
    """Test that quantity is an integer"""
    assert isinstance(order.quantity, int)


def test_quantity_positive():
    """Test that quantity is positive"""
    assert order.quantity > 0


def test_price_per_drink_exists():
    """Test that price_per_drink variable exists"""
    assert hasattr(order, 'price_per_drink')


def test_price_per_drink_is_float():
    """Test that price_per_drink is a float"""
    assert isinstance(order.price_per_drink, float)


def test_price_per_drink_positive():
    """Test that price_per_drink is positive"""
    assert order.price_per_drink > 0


def test_total_price_exists():
    """Test that total_price variable exists"""
    assert hasattr(order, 'total_price')


def test_total_price_calculated_correctly():
    """Test that total_price is calculated correctly"""
    expected = order.quantity * order.price_per_drink
    assert abs(order.total_price - expected) < 0.01


def test_is_loyalty_member_exists():
    """Test that is_loyalty_member variable exists"""
    assert hasattr(order, 'is_loyalty_member')


def test_is_loyalty_member_is_boolean():
    """Test that is_loyalty_member is a boolean"""
    assert isinstance(order.is_loyalty_member, bool)


def test_discount_amount_exists():
    """Test that discount_amount variable exists"""
    assert hasattr(order, 'discount_amount')


def test_discount_amount_is_numeric():
    """Test that discount_amount is a number"""
    assert isinstance(order.discount_amount, (int, float))


def test_discount_amount_correct():
    """Test that discount_amount is calculated correctly based on loyalty status"""
    if order.is_loyalty_member:
        expected = order.total_price * 0.10
        assert abs(order.discount_amount - expected) < 0.01
    else:
        assert order.discount_amount == 0.0


def test_final_price_exists():
    """Test that final_price variable exists"""
    assert hasattr(order, 'final_price')


def test_final_price_is_numeric():
    """Test that final_price is a number"""
    assert isinstance(order.final_price, (int, float))


def test_final_price_calculated_correctly():
    """Test that final_price is calculated correctly"""
    expected = order.total_price - order.discount_amount
    assert abs(order.final_price - expected) < 0.01


def test_final_price_positive():
    """Test that final_price is positive"""
    assert order.final_price > 0
