"""
Test file for Playlist Manager exercise
Generated by Copilot
"""

import pytest
import sys
from pathlib import Path

# Add the exercise directory to the path
sys.path.insert(0, str(Path(__file__).parent))

import playlist


class TestAddSong:
    """Tests for add_song function"""
    
    def test_add_to_empty_list(self):
        """Test adding a song to an empty playlist"""
        result = playlist.add_song([], "First Song")
        assert result == ["First Song"]
    
    def test_add_to_existing_list(self):
        """Test adding a song to a playlist with existing songs"""
        songs = ["Song A", "Song B"]
        result = playlist.add_song(songs, "Song C")
        assert result == ["Song A", "Song B", "Song C"]
    
    def test_add_modifies_original(self):
        """Test that add_song modifies the original list"""
        songs = ["Song A"]
        result = playlist.add_song(songs, "Song B")
        assert songs is result  # Same object


class TestRemoveSong:
    """Tests for remove_song function"""
    
    def test_remove_existing_song(self):
        """Test removing a song that exists"""
        songs = ["Song A", "Song B", "Song C"]
        result = playlist.remove_song(songs, "Song B")
        assert result == ["Song A", "Song C"]
    
    def test_remove_first_occurrence(self):
        """Test that only the first occurrence is removed"""
        songs = ["Song A", "Song B", "Song A"]
        result = playlist.remove_song(songs, "Song A")
        assert result == ["Song B", "Song A"]
    
    def test_remove_nonexistent_song(self):
        """Test removing a song that doesn't exist"""
        songs = ["Song A", "Song B"]
        result = playlist.remove_song(songs, "Song C")
        assert result == ["Song A", "Song B"]
    
    def test_remove_case_sensitive(self):
        """Test that removal is case-sensitive"""
        songs = ["Song A", "song a"]
        result = playlist.remove_song(songs, "Song A")
        assert result == ["song a"]


class TestGetSongAtPosition:
    """Tests for get_song_at_position function"""
    
    def test_get_first_song(self):
        """Test getting the first song"""
        songs = ["First", "Second", "Third"]
        assert playlist.get_song_at_position(songs, 0) == "First"
    
    def test_get_middle_song(self):
        """Test getting a song from the middle"""
        songs = ["First", "Second", "Third"]
        assert playlist.get_song_at_position(songs, 1) == "Second"
    
    def test_get_last_song(self):
        """Test getting the last song"""
        songs = ["First", "Second", "Third"]
        assert playlist.get_song_at_position(songs, 2) == "Third"
    
    def test_get_invalid_positive_position(self):
        """Test getting a position beyond the list length"""
        songs = ["First", "Second"]
        assert playlist.get_song_at_position(songs, 5) == "Invalid position"
    
    def test_get_invalid_negative_position(self):
        """Test getting a negative position"""
        songs = ["First", "Second"]
        assert playlist.get_song_at_position(songs, -1) == "Invalid position"


class TestGetFirstThree:
    """Tests for get_first_three function"""
    
    def test_get_first_three_from_long_list(self):
        """Test getting first three from a longer list"""
        songs = ["A", "B", "C", "D", "E"]
        result = playlist.get_first_three(songs)
        assert result == ["A", "B", "C"]
    
    def test_get_first_three_exact(self):
        """Test with exactly three songs"""
        songs = ["A", "B", "C"]
        result = playlist.get_first_three(songs)
        assert result == ["A", "B", "C"]
    
    def test_get_first_three_from_short_list(self):
        """Test with fewer than three songs"""
        songs = ["A", "B"]
        result = playlist.get_first_three(songs)
        assert result == ["A", "B"]
    
    def test_get_first_three_from_empty(self):
        """Test with empty playlist"""
        result = playlist.get_first_three([])
        assert result == []
    
    def test_get_first_three_returns_new_list(self):
        """Test that a new list is returned"""
        songs = ["A", "B", "C", "D"]
        result = playlist.get_first_three(songs)
        assert result is not songs  # Different objects


class TestReversePlaylist:
    """Tests for reverse_playlist function"""
    
    def test_reverse_multiple_songs(self):
        """Test reversing a playlist with multiple songs"""
        songs = ["First", "Second", "Third"]
        result = playlist.reverse_playlist(songs)
        assert result == ["Third", "Second", "First"]
    
    def test_reverse_single_song(self):
        """Test reversing a playlist with one song"""
        result = playlist.reverse_playlist(["Only"])
        assert result == ["Only"]
    
    def test_reverse_empty(self):
        """Test reversing an empty playlist"""
        result = playlist.reverse_playlist([])
        assert result == []
    
    def test_reverse_does_not_modify_original(self):
        """Test that original list is not modified"""
        songs = ["A", "B", "C"]
        result = playlist.reverse_playlist(songs)
        assert songs == ["A", "B", "C"]
        assert result is not songs


class TestTotalSongs:
    """Tests for total_songs function"""
    
    def test_count_multiple_songs(self):
        """Test counting songs in a playlist"""
        songs = ["A", "B", "C", "D"]
        assert playlist.total_songs(songs) == 4
    
    def test_count_empty_playlist(self):
        """Test counting an empty playlist"""
        assert playlist.total_songs([]) == 0
    
    def test_count_single_song(self):
        """Test counting a single song"""
        assert playlist.total_songs(["Only"]) == 1


class TestContainsSong:
    """Tests for contains_song function"""
    
    def test_contains_existing_song(self):
        """Test checking for a song that exists"""
        songs = ["Song A", "Song B", "Song C"]
        assert playlist.contains_song(songs, "Song B") is True
    
    def test_contains_nonexistent_song(self):
        """Test checking for a song that doesn't exist"""
        songs = ["Song A", "Song B"]
        assert playlist.contains_song(songs, "Song C") is False
    
    def test_contains_case_sensitive(self):
        """Test that search is case-sensitive"""
        songs = ["Song A", "song a"]
        assert playlist.contains_song(songs, "Song A") is True
        assert playlist.contains_song(songs, "SONG A") is False
    
    def test_contains_in_empty_playlist(self):
        """Test searching in an empty playlist"""
        assert playlist.contains_song([], "Any Song") is False


class TestCombinePlaylists:
    """Tests for combine_playlists function"""
    
    def test_combine_two_playlists(self):
        """Test combining two playlists"""
        list1 = ["A", "B"]
        list2 = ["C", "D"]
        result = playlist.combine_playlists(list1, list2)
        assert result == ["A", "B", "C", "D"]
    
    def test_combine_with_empty_first(self):
        """Test combining when first playlist is empty"""
        result = playlist.combine_playlists([], ["A", "B"])
        assert result == ["A", "B"]
    
    def test_combine_with_empty_second(self):
        """Test combining when second playlist is empty"""
        result = playlist.combine_playlists(["A", "B"], [])
        assert result == ["A", "B"]
    
    def test_combine_both_empty(self):
        """Test combining two empty playlists"""
        result = playlist.combine_playlists([], [])
        assert result == []
    
    def test_combine_returns_new_list(self):
        """Test that a new list is returned"""
        list1 = ["A"]
        list2 = ["B"]
        result = playlist.combine_playlists(list1, list2)
        assert result is not list1
        assert result is not list2
