"""
Test file for Text Message Processor exercise
Generated by Copilot
"""

import pytest
import sys
from pathlib import Path

# Add the exercise directory to the path
sys.path.insert(0, str(Path(__file__).parent))

import text_processor


class TestNormalizeText:
    """Tests for normalize_text function"""
    
    def test_normalize_with_spaces(self):
        """Test normalizing text with leading and trailing spaces"""
        result = text_processor.normalize_text("  Hello World  ")
        assert result == "hello world"
    
    def test_normalize_uppercase(self):
        """Test normalizing uppercase text"""
        result = text_processor.normalize_text("HELLO")
        assert result == "hello"
    
    def test_normalize_mixed_case(self):
        """Test normalizing mixed case text"""
        result = text_processor.normalize_text("  HeLLo WoRLd  ")
        assert result == "hello world"
    
    def test_normalize_no_spaces(self):
        """Test normalizing text without extra spaces"""
        result = text_processor.normalize_text("hello")
        assert result == "hello"


class TestCountWords:
    """Tests for count_words function"""
    
    def test_count_multiple_words(self):
        """Test counting multiple words"""
        result = text_processor.count_words("Hello world from Python")
        assert result == 4
    
    def test_count_single_word(self):
        """Test counting a single word"""
        result = text_processor.count_words("Hello")
        assert result == 1
    
    def test_count_empty_string(self):
        """Test counting words in an empty string"""
        result = text_processor.count_words("")
        assert result == 0
    
    def test_count_with_extra_spaces(self):
        """Test counting words with extra spaces"""
        result = text_processor.count_words("Hello   world")
        assert result == 2


class TestIsShouting:
    """Tests for is_shouting function"""
    
    def test_shouting_all_caps(self):
        """Test detecting shouting with all caps"""
        assert text_processor.is_shouting("HELLO") is True
    
    def test_shouting_with_punctuation(self):
        """Test shouting with punctuation"""
        assert text_processor.is_shouting("HELLO!") is True
    
    def test_not_shouting_lowercase(self):
        """Test not shouting with lowercase"""
        assert text_processor.is_shouting("hello") is False
    
    def test_not_shouting_mixed_case(self):
        """Test not shouting with mixed case"""
        assert text_processor.is_shouting("Hello") is False
    
    def test_shouting_empty_string(self):
        """Test empty string is not shouting"""
        assert text_processor.is_shouting("") is False
    
    def test_shouting_only_numbers(self):
        """Test string with only numbers is not shouting"""
        assert text_processor.is_shouting("123") is False


class TestCensorWord:
    """Tests for censor_word function"""
    
    def test_censor_single_occurrence(self):
        """Test censoring a single occurrence"""
        result = text_processor.censor_word("Hello world", "world")
        assert result == "Hello *****"
    
    def test_censor_multiple_occurrences(self):
        """Test censoring multiple occurrences"""
        result = text_processor.censor_word("Hello world, hello!", "hello")
        assert result == "***** world, *****!"
    
    def test_censor_case_insensitive(self):
        """Test that censoring is case-insensitive"""
        result = text_processor.censor_word("Hello HELLO hello", "hello")
        assert result == "***** ***** *****"
    
    def test_censor_no_match(self):
        """Test censoring when word is not found"""
        result = text_processor.censor_word("Hello world", "goodbye")
        assert result == "Hello world"
    
    def test_censor_different_lengths(self):
        """Test censoring words of different lengths"""
        result = text_processor.censor_word("bad word", "bad")
        assert result == "*** word"


class TestCreateAcronym:
    """Tests for create_acronym function"""
    
    def test_acronym_simple(self):
        """Test creating a simple acronym"""
        result = text_processor.create_acronym("as soon as possible")
        assert result == "ASAP"
    
    def test_acronym_multiple_words(self):
        """Test acronym with multiple words"""
        result = text_processor.create_acronym("laugh out loud")
        assert result == "LOL"
    
    def test_acronym_single_word(self):
        """Test acronym with single word"""
        result = text_processor.create_acronym("hello")
        assert result == "H"
    
    def test_acronym_mixed_case(self):
        """Test acronym with mixed case input"""
        result = text_processor.create_acronym("Hello World Test")
        assert result == "HWT"


class TestReverseWords:
    """Tests for reverse_words function"""
    
    def test_reverse_two_words(self):
        """Test reversing two words"""
        result = text_processor.reverse_words("Hello world")
        assert result == "world Hello"
    
    def test_reverse_multiple_words(self):
        """Test reversing multiple words"""
        result = text_processor.reverse_words("one two three four")
        assert result == "four three two one"
    
    def test_reverse_single_word(self):
        """Test reversing a single word"""
        result = text_processor.reverse_words("hello")
        assert result == "hello"


class TestIsValidEmail:
    """Tests for is_valid_email function"""
    
    def test_valid_email_basic(self):
        """Test a basic valid email"""
        assert text_processor.is_valid_email("test@example.com") is True
    
    def test_valid_email_subdomain(self):
        """Test a valid email with subdomain"""
        assert text_processor.is_valid_email("user@mail.example.com") is True
    
    def test_invalid_no_at(self):
        """Test invalid email without @"""
        assert text_processor.is_valid_email("testexample.com") is False
    
    def test_invalid_multiple_at(self):
        """Test invalid email with multiple @"""
        assert text_processor.is_valid_email("test@@example.com") is False
    
    def test_invalid_no_domain(self):
        """Test invalid email without domain"""
        assert text_processor.is_valid_email("test@") is False
    
    def test_invalid_no_local(self):
        """Test invalid email without local part"""
        assert text_processor.is_valid_email("@example.com") is False
    
    def test_invalid_no_dot(self):
        """Test invalid email without dot after @"""
        assert text_processor.is_valid_email("test@example") is False


class TestExtractNumbers:
    """Tests for extract_numbers function"""
    
    def test_extract_single_number(self):
        """Test extracting a single number"""
        result = text_processor.extract_numbers("I have 2 cats")
        assert result == [2]
    
    def test_extract_multiple_numbers(self):
        """Test extracting multiple numbers"""
        result = text_processor.extract_numbers("I have 2 cats and 3 dogs")
        assert result == [2, 3]
    
    def test_extract_no_numbers(self):
        """Test extracting when there are no numbers"""
        result = text_processor.extract_numbers("Hello world")
        assert result == []
    
    def test_extract_mixed_content(self):
        """Test extracting from mixed content"""
        result = text_processor.extract_numbers("Buy 10 apples, 5 oranges, and 3 bananas")
        assert result == [10, 5, 3]
    
    def test_extract_only_numbers(self):
        """Test extracting when string is only numbers"""
        result = text_processor.extract_numbers("1 2 3 4 5")
        assert result == [1, 2, 3, 4, 5]
