"""
Test file for Dungeon Explorer exercise
Generated by Copilot
"""

import pytest
import sys
from pathlib import Path

# Add the exercise directory to the path
sys.path.insert(0, str(Path(__file__).parent))

import dungeon


class TestCanOpenChest:
    """Tests for can_open_chest function"""
    
    def test_open_with_key(self):
        """Test opening a locked chest with a key"""
        assert dungeon.can_open_chest(True, True, 5) == "Chest opened!"
    
    def test_open_unlocked_chest(self):
        """Test opening an unlocked chest"""
        assert dungeon.can_open_chest(False, False, 5) == "Chest opened!"
    
    def test_open_with_high_strength(self):
        """Test opening with high strength"""
        assert dungeon.can_open_chest(False, True, 15) == "Chest opened!"
    
    def test_cannot_open_chest(self):
        """Test chest remains closed"""
        assert dungeon.can_open_chest(False, True, 5) == "Chest remains closed"
    
    def test_strength_exactly_10(self):
        """Test with strength exactly 10 (should not open)"""
        assert dungeon.can_open_chest(False, True, 10) == "Chest remains closed"
    
    def test_strength_11(self):
        """Test with strength 11 (should open)"""
        assert dungeon.can_open_chest(False, True, 11) == "Chest opened!"


class TestExploreRoom:
    """Tests for explore_room function"""
    
    def test_dark_cave_with_torch(self):
        """Test exploring dark cave with torch"""
        assert dungeon.explore_room("dark_cave", True) == "You found a treasure chest!"
    
    def test_dark_cave_without_torch(self):
        """Test exploring dark cave without torch"""
        assert dungeon.explore_room("dark_cave", False) == "Too dark to explore"
    
    def test_library(self):
        """Test exploring library (torch doesn't matter)"""
        assert dungeon.explore_room("library", True) == "You found an ancient book"
        assert dungeon.explore_room("library", False) == "You found an ancient book"
    
    def test_armory_with_torch(self):
        """Test exploring armory with torch"""
        assert dungeon.explore_room("armory", True) == "You found a legendary sword!"
    
    def test_armory_without_torch(self):
        """Test exploring armory without torch"""
        assert dungeon.explore_room("armory", False) == "Too dark to explore"
    
    def test_unknown_room(self):
        """Test exploring unknown room type"""
        assert dungeon.explore_room("kitchen", True) == "Nothing interesting here"
        assert dungeon.explore_room("bathroom", False) == "Nothing interesting here"


class TestCountMonstersInDungeon:
    """Tests for count_monsters_in_dungeon function"""
    
    def test_count_two_monsters(self):
        """Test counting monsters in a simple dungeon"""
        dungeon_map = [["empty", "monster"], ["monster", "treasure"]]
        assert dungeon.count_monsters_in_dungeon(dungeon_map) == 2
    
    def test_count_no_monsters(self):
        """Test dungeon with no monsters"""
        dungeon_map = [["empty", "treasure"], ["empty", "empty"]]
        assert dungeon.count_monsters_in_dungeon(dungeon_map) == 0
    
    def test_count_all_monsters(self):
        """Test dungeon full of monsters"""
        dungeon_map = [["monster", "monster"], ["monster", "monster"]]
        assert dungeon.count_monsters_in_dungeon(dungeon_map) == 4
    
    def test_count_case_insensitive(self):
        """Test that counting is case-insensitive"""
        dungeon_map = [["Monster", "MONSTER"], ["monster", "empty"]]
        assert dungeon.count_monsters_in_dungeon(dungeon_map) == 3
    
    def test_count_larger_dungeon(self):
        """Test counting in a larger dungeon"""
        dungeon_map = [
            ["empty", "monster", "empty"],
            ["treasure", "monster", "monster"],
            ["empty", "empty", "monster"]
        ]
        assert dungeon.count_monsters_in_dungeon(dungeon_map) == 4


class TestFindTreasurePosition:
    """Tests for find_treasure_position function"""
    
    def test_find_treasure_basic(self):
        """Test finding treasure in a simple dungeon"""
        dungeon_map = [["empty", "monster"], ["treasure", "empty"]]
        assert dungeon.find_treasure_position(dungeon_map) == (1, 0)
    
    def test_find_treasure_top_right(self):
        """Test finding treasure in top right"""
        dungeon_map = [["empty", "treasure"], ["monster", "empty"]]
        assert dungeon.find_treasure_position(dungeon_map) == (0, 1)
    
    def test_treasure_not_found(self):
        """Test when treasure is not in the dungeon"""
        dungeon_map = [["empty", "monster"], ["empty", "empty"]]
        assert dungeon.find_treasure_position(dungeon_map) is None
    
    def test_find_treasure_case_insensitive(self):
        """Test that search is case-insensitive"""
        dungeon_map = [["empty", "TREASURE"], ["monster", "empty"]]
        assert dungeon.find_treasure_position(dungeon_map) == (0, 1)
    
    def test_find_first_treasure(self):
        """Test that first treasure is returned when multiple exist"""
        dungeon_map = [["treasure", "empty"], ["treasure", "empty"]]
        result = dungeon.find_treasure_position(dungeon_map)
        assert result == (0, 0)


class TestCalculateDamage:
    """Tests for calculate_damage function"""
    
    def test_calculate_mixed_attacks(self):
        """Test calculating damage from mixed attack types"""
        attacks = [
            {"type": "critical", "power": 10},
            {"type": "normal", "power": 5}
        ]
        assert dungeon.calculate_damage(attacks) == 25
    
    def test_calculate_all_critical(self):
        """Test all critical attacks"""
        attacks = [
            {"type": "critical", "power": 5},
            {"type": "critical", "power": 10}
        ]
        assert dungeon.calculate_damage(attacks) == 30
    
    def test_calculate_all_normal(self):
        """Test all normal attacks"""
        attacks = [
            {"type": "normal", "power": 10},
            {"type": "normal", "power": 15}
        ]
        assert dungeon.calculate_damage(attacks) == 25
    
    def test_calculate_with_weak(self):
        """Test with weak attacks"""
        attacks = [
            {"type": "weak", "power": 10},
            {"type": "normal", "power": 5}
        ]
        assert dungeon.calculate_damage(attacks) == 10
    
    def test_calculate_no_attacks(self):
        """Test with no attacks"""
        assert dungeon.calculate_damage([]) == 0


class TestSafePathExists:
    """Tests for safe_path_exists function"""
    
    def test_safe_path_all_safe(self):
        """Test with all safe cells"""
        grid = [["safe", "safe"], ["safe", "safe"]]
        assert dungeon.safe_path_exists(grid, 0, 0) is True
    
    def test_safe_path_blocked(self):
        """Test with blocked path"""
        grid = [["safe", "trap"], ["trap", "safe"]]
        assert dungeon.safe_path_exists(grid, 0, 0) is False
    
    def test_safe_path_right_then_down(self):
        """Test path going right then down"""
        grid = [["safe", "safe", "safe"], ["trap", "trap", "safe"]]
        assert dungeon.safe_path_exists(grid, 0, 0) is True
    
    def test_unsafe_start(self):
        """Test with unsafe starting position"""
        grid = [["trap", "safe"], ["safe", "safe"]]
        assert dungeon.safe_path_exists(grid, 0, 0) is False
    
    def test_single_cell(self):
        """Test with single cell grid"""
        assert dungeon.safe_path_exists([["safe"]], 0, 0) is True
        assert dungeon.safe_path_exists([["trap"]], 0, 0) is False


class TestGeneratePattern:
    """Tests for generate_pattern function"""
    
    def test_generate_2x3(self):
        """Test generating a 2x3 pattern"""
        result = dungeon.generate_pattern(2, 3, "X")
        expected = [["X", "X", "X"], ["X", "X", "X"]]
        assert result == expected
    
    def test_generate_3x2(self):
        """Test generating a 3x2 pattern"""
        result = dungeon.generate_pattern(3, 2, "O")
        expected = [["O", "O"], ["O", "O"], ["O", "O"]]
        assert result == expected
    
    def test_generate_1x1(self):
        """Test generating a 1x1 pattern"""
        result = dungeon.generate_pattern(1, 1, "*")
        assert result == [["*"]]
    
    def test_generate_different_char(self):
        """Test generating with different character"""
        result = dungeon.generate_pattern(2, 2, "#")
        assert result == [["#", "#"], ["#", "#"]]


class TestGetRoomTypes:
    """Tests for get_room_types function"""
    
    def test_count_room_types_basic(self):
        """Test counting room types in a simple dungeon"""
        dungeon_map = [["empty", "monster"], ["empty", "treasure"]]
        result = dungeon.get_room_types(dungeon_map)
        assert result == {"empty": 2, "monster": 1, "treasure": 1}
    
    def test_count_room_types_all_same(self):
        """Test when all rooms are the same type"""
        dungeon_map = [["empty", "empty"], ["empty", "empty"]]
        result = dungeon.get_room_types(dungeon_map)
        assert result == {"empty": 4}
    
    def test_count_room_types_larger(self):
        """Test with a larger dungeon"""
        dungeon_map = [
            ["empty", "monster", "empty"],
            ["treasure", "monster", "trap"],
            ["empty", "exit", "empty"]
        ]
        result = dungeon.get_room_types(dungeon_map)
        assert result == {"empty": 5, "monster": 2, "treasure": 1, "trap": 1, "exit": 1}
    
    def test_count_empty_dungeon(self):
        """Test with empty dungeon"""
        result = dungeon.get_room_types([])
        assert result == {}
