"""
Student Gradebook - Dictionaries Exercise
Generated by Copilot
"""


def create_student(name: str, grade: int) -> dict:
    """
    Create a student dictionary with name and grade.
    
    Args:
        name: The student's name
        grade: The student's grade
    
    Returns:
        A dictionary with keys "name" and "grade"
    """
    # TODO: Create and return a dictionary with "name" and "grade" keys
    pass


def get_student_grade(student: dict) -> int:
    """
    Get the grade from a student dictionary.
    
    Args:
        student: A dictionary containing student information
    
    Returns:
        The student's grade
    """
    # TODO: Return the value associated with the "grade" key
    pass


def update_grade(student: dict, new_grade: int) -> dict:
    """
    Update a student's grade.
    
    Args:
        student: A dictionary containing student information
        new_grade: The new grade value
    
    Returns:
        The modified student dictionary
    """
    # TODO: Update the "grade" key with new_grade and return the dictionary
    pass


def add_subject(student: dict, subject: str, score: int) -> dict:
    """
    Add a subject and score to a student dictionary.
    
    Args:
        student: A dictionary containing student information
        subject: The subject name
        score: The score for that subject
    
    Returns:
        The modified student dictionary
    """
    # TODO: Add a new key-value pair to the dictionary and return it
    pass


def get_all_subjects(student: dict) -> list[str]:
    """
    Get all keys from a student dictionary.
    
    Args:
        student: A dictionary containing student information
    
    Returns:
        A list of all keys in the dictionary
    """
    # TODO: Return a list of all keys in the student dictionary
    pass


def get_average_score(scores: dict[str, int]) -> float:
    """
    Calculate the average of all scores in a dictionary.
    
    Args:
        scores: A dictionary mapping subjects to scores
    
    Returns:
        The average score, or 0.0 if the dictionary is empty
    """
    # TODO: Calculate and return the average of all values
    # Remember to handle the empty dictionary case
    pass


def student_exists(gradebook: dict[str, int], student_name: str) -> bool:
    """
    Check if a student exists in the gradebook.
    
    Args:
        gradebook: A dictionary mapping student names to grades
        student_name: The name to search for
    
    Returns:
        True if the student exists, False otherwise
    """
    # TODO: Check if student_name is a key in the gradebook
    pass


def combine_gradebooks(gradebook1: dict, gradebook2: dict) -> dict:
    """
    Combine two gradebook dictionaries.
    
    Args:
        gradebook1: The first gradebook dictionary
        gradebook2: The second gradebook dictionary
    
    Returns:
        A new dictionary containing all entries from both gradebooks.
        If a key exists in both, use the value from gradebook2.
    """
    # TODO: Combine the two dictionaries and return the result
    pass
