"""
Test file for Student Gradebook exercise
Generated by Copilot
"""

import pytest
import sys
from pathlib import Path

# Add the exercise directory to the path
sys.path.insert(0, str(Path(__file__).parent))

import gradebook


class TestCreateStudent:
    """Tests for create_student function"""
    
    def test_create_student_basic(self):
        """Test creating a basic student dictionary"""
        result = gradebook.create_student("Alice", 85)
        assert result == {"name": "Alice", "grade": 85}
    
    def test_create_student_different_values(self):
        """Test creating a student with different values"""
        result = gradebook.create_student("Bob", 92)
        assert result == {"name": "Bob", "grade": 92}
    
    def test_create_student_returns_dict(self):
        """Test that the function returns a dictionary"""
        result = gradebook.create_student("Charlie", 78)
        assert isinstance(result, dict)


class TestGetStudentGrade:
    """Tests for get_student_grade function"""
    
    def test_get_grade_basic(self):
        """Test getting a grade from a student dictionary"""
        student = {"name": "Alice", "grade": 85}
        assert gradebook.get_student_grade(student) == 85
    
    def test_get_grade_different_value(self):
        """Test getting a different grade value"""
        student = {"name": "Bob", "grade": 92}
        assert gradebook.get_student_grade(student) == 92


class TestUpdateGrade:
    """Tests for update_grade function"""
    
    def test_update_grade_basic(self):
        """Test updating a student's grade"""
        student = {"name": "Alice", "grade": 85}
        result = gradebook.update_grade(student, 90)
        assert result["grade"] == 90
    
    def test_update_grade_modifies_original(self):
        """Test that the original dictionary is modified"""
        student = {"name": "Bob", "grade": 78}
        result = gradebook.update_grade(student, 82)
        assert student is result
        assert student["grade"] == 82
    
    def test_update_grade_preserves_other_keys(self):
        """Test that other keys are preserved"""
        student = {"name": "Charlie", "grade": 75, "age": 20}
        result = gradebook.update_grade(student, 80)
        assert result["name"] == "Charlie"
        assert result["age"] == 20


class TestAddSubject:
    """Tests for add_subject function"""
    
    def test_add_subject_basic(self):
        """Test adding a subject to a student dictionary"""
        student = {"name": "Alice", "grade": 85}
        result = gradebook.add_subject(student, "math", 90)
        assert result["math"] == 90
    
    def test_add_subject_multiple(self):
        """Test adding multiple subjects"""
        student = {"name": "Bob", "grade": 80}
        gradebook.add_subject(student, "math", 85)
        gradebook.add_subject(student, "science", 88)
        assert student["math"] == 85
        assert student["science"] == 88
    
    def test_add_subject_preserves_existing(self):
        """Test that existing keys are preserved"""
        student = {"name": "Charlie", "grade": 75}
        result = gradebook.add_subject(student, "history", 82)
        assert result["name"] == "Charlie"
        assert result["grade"] == 75


class TestGetAllSubjects:
    """Tests for get_all_subjects function"""
    
    def test_get_all_subjects_basic(self):
        """Test getting all subjects from a student dictionary"""
        student = {"name": "Alice", "grade": 85, "math": 90}
        result = gradebook.get_all_subjects(student)
        assert set(result) == {"name", "grade", "math"}
    
    def test_get_all_subjects_returns_list(self):
        """Test that a list is returned"""
        student = {"name": "Bob", "grade": 80}
        result = gradebook.get_all_subjects(student)
        assert isinstance(result, list)
    
    def test_get_all_subjects_empty(self):
        """Test with an empty dictionary"""
        result = gradebook.get_all_subjects({})
        assert result == []
    
    def test_get_all_subjects_many_keys(self):
        """Test with multiple subjects"""
        student = {"name": "Charlie", "grade": 85, "math": 90, "science": 88, "history": 82}
        result = gradebook.get_all_subjects(student)
        assert len(result) == 5
        assert "math" in result
        assert "science" in result


class TestGetAverageScore:
    """Tests for get_average_score function"""
    
    def test_average_score_basic(self):
        """Test calculating average of two scores"""
        scores = {"math": 90, "science": 80}
        assert gradebook.get_average_score(scores) == 85.0
    
    def test_average_score_three_subjects(self):
        """Test with three subjects"""
        scores = {"math": 90, "science": 85, "history": 95}
        assert gradebook.get_average_score(scores) == 90.0
    
    def test_average_score_empty(self):
        """Test with empty dictionary"""
        assert gradebook.get_average_score({}) == 0.0
    
    def test_average_score_single(self):
        """Test with single score"""
        scores = {"math": 88}
        assert gradebook.get_average_score(scores) == 88.0
    
    def test_average_score_returns_float(self):
        """Test that a float is returned"""
        scores = {"math": 85, "science": 90}
        result = gradebook.get_average_score(scores)
        assert isinstance(result, float)


class TestStudentExists:
    """Tests for student_exists function"""
    
    def test_student_exists_true(self):
        """Test checking for an existing student"""
        gradebook_dict = {"Alice": 85, "Bob": 90, "Charlie": 78}
        assert gradebook.student_exists(gradebook_dict, "Alice") is True
    
    def test_student_exists_false(self):
        """Test checking for a non-existent student"""
        gradebook_dict = {"Alice": 85, "Bob": 90}
        assert gradebook.student_exists(gradebook_dict, "Charlie") is False
    
    def test_student_exists_case_sensitive(self):
        """Test that the check is case-sensitive"""
        gradebook_dict = {"Alice": 85}
        assert gradebook.student_exists(gradebook_dict, "alice") is False
    
    def test_student_exists_empty(self):
        """Test with empty gradebook"""
        assert gradebook.student_exists({}, "Anyone") is False


class TestCombineGradebooks:
    """Tests for combine_gradebooks function"""
    
    def test_combine_no_overlap(self):
        """Test combining gradebooks with no overlapping keys"""
        gb1 = {"Alice": 85, "Bob": 90}
        gb2 = {"Charlie": 88, "Diana": 92}
        result = gradebook.combine_gradebooks(gb1, gb2)
        assert result == {"Alice": 85, "Bob": 90, "Charlie": 88, "Diana": 92}
    
    def test_combine_with_overlap(self):
        """Test combining gradebooks with overlapping keys"""
        gb1 = {"Alice": 85, "Bob": 90}
        gb2 = {"Bob": 95, "Charlie": 88}
        result = gradebook.combine_gradebooks(gb1, gb2)
        assert result["Alice"] == 85
        assert result["Bob"] == 95  # Value from gb2
        assert result["Charlie"] == 88
    
    def test_combine_empty_first(self):
        """Test combining when first gradebook is empty"""
        gb1 = {}
        gb2 = {"Alice": 85, "Bob": 90}
        result = gradebook.combine_gradebooks(gb1, gb2)
        assert result == {"Alice": 85, "Bob": 90}
    
    def test_combine_empty_second(self):
        """Test combining when second gradebook is empty"""
        gb1 = {"Alice": 85, "Bob": 90}
        gb2 = {}
        result = gradebook.combine_gradebooks(gb1, gb2)
        assert result == {"Alice": 85, "Bob": 90}
    
    def test_combine_both_empty(self):
        """Test combining two empty gradebooks"""
        result = gradebook.combine_gradebooks({}, {})
        assert result == {}
    
    def test_combine_returns_new_dict(self):
        """Test that a new dictionary is returned"""
        gb1 = {"Alice": 85}
        gb2 = {"Bob": 90}
        result = gradebook.combine_gradebooks(gb1, gb2)
        assert result is not gb1
        assert result is not gb2
